{application,hangman,
             [{applications,[kernel,stdlib,elixir,logger,dictionary]},
              {description,"hangman"},
              {modules,['Elixir.Hangman','Elixir.Hangman.Application',
                        'Elixir.Hangman.Game','Elixir.Hangman.Server',
                        'Elixir.Hangman.Tally']},
              {registered,[]},
              {vsn,"0.1.0"},
              {mod,{'Elixir.Hangman.Application',[]}}]}.
